sslnew always exits with EXIT failure
openssl/perftools pull request #7
Opened 2024-08-27 09:25 UTC by Sashan

Fixes: 5

2024-08-27 09:40 UTC, quarckster commented on source/sslnew.c
> +    rc = 0;
do we really everything else except this line on this PR?

2024-08-27 09:59 UTC, mattcaswell requested changes
It seems we have a spurious additional commit in this PR.

2024-08-27 09:59 UTC, mattcaswell commented on source/sslnew.c
> +    rc = 0;
Better would be to use `rc = EXIT_SUCCESS` (since we initialise it with `EXIT_FAILURE`)

2024-08-27 10:08 UTC, mattcaswell approved these changes

2024-08-27 10:10 UTC, t8m approved these changes

2024-08-29 07:12 UTC, t8m commented
Merged. Thank you.

2024-08-29 07:12 UTC, closed without merging